### ISSUE TITLE
SFC | Error in standards of new members

### ISSUE THREAD

**Issue by LewisSokoll** [EXYZED/LNDN_PublicDatabase#15]
Leading Case Study NCA Agent - @LewisSokoll 
NCA Supervisor - @EXYZED

**Comment by EXYZED** [comment]
- Test

**Comment by LewisSokoll** [comment]
Currently gaining evidence from earlier conduct issue.

SUSPECT: Jack_Lopez

WITNESS: General EXYZED
                Assistant Commissioner TheWiseAce

VICTIMS: EXYZED
               Sodium_Chloride

**Comment by EXYZED** [comment]
Jack_Lopez
-----------------------
Violations caused
- Shooting of a unarmed civilian (Death caused) *1
- Causing injury to a high ranking commander *2
- Unauthorised discharges from groups (DSU)
- Unacceptable language/attitude towards a another officer. *2

*1 - Sodium_Chloride
*2 - EXYZED

**Comment by LewisSokoll** [comment]
Statement from Sodium_Chloride:

> He shot and killed my thinking I was a threat and almost killed EXYZED, he realised his mistake and was very sorry for his actions, I don't think he meant to do it however it was silly of him. EXYZED had me arrested and almost died in the process. We all make mistakes, however, mistakes have consequences, I don't honestly care that he killed me however what concerns me is his extreme lack of simple judgement, he said he presumed I was shooting at him because he was shot in "my general direction" so instantly opened fire on me. An assumption that was ultimately wrong

**Comment by LewisSokoll** [comment]
TO DO LIST:

- [✔]  Get a statement from Sodium_Chloride

- [✘] Get a statement from @EXYZED 

- [✘] Get a statement from Jack_Lopez
