### ISSUE TITLE
Concerns of Abuse : Pengblock, mitchellnip [Internal]

### ISSUE THREAD

**Issue by LewisSokoll** [EXYZED/LNDN_PublicDatabase#17]
Leading Case Study NCA Agent - @LewisSokoll
NCA Supervisor - @EXYZED

Proof and statement by Terrificgamer1:
https://cdn.discordapp.com/attachments/297468089006686208/299958229557837824/image.jpg
https://cdn.discordapp.com/attachments/297468089006686208/299958241448689664/image.jpg

> A commander shouts "allau akbu" then aa'ss at mocks which he is a commander and also pengblock AS well has aa'ed
and peng is a chief sup

The commander referenced in the above statement is now found to be DSU Commander mitchellnip.

**Comment by LewisSokoll** [comment]
Statement from EpicDoge417:

> What happened was, was PengBlock was winding everyone up when Mitch was doing a training. Peng used :nuke when mitch was doing it. Over and over again Peng carried on. So mitch used :smite peng,  as mitch got so annoyed with Peng.
We were just training.
And he interrupted by blowing it all up.

**Comment by LewisSokoll** [comment]
Statement from CallOfDuty463:

> Peng was interrupting Mitch's training a she was using :nuke serval times. After      Peng annoyed Mitch so much, Mitch used :smite Peng. It didn't do anything to him due to them being the same level. Then Peng teamed him self British army and said he wanted to do a fire drill.

**Comment by LewisSokoll** [comment]
Statement from Pengblock:

> I do admit to AA, however I swear on my granddads life that I won't again. I love this force and I really don't want to be exiled.

**Comment by LewisSokoll** [comment]
Statement from Crazybluebones:

> Basically, what happened was Peng was using commands such as :nuke and :sm Allu Akbar. The nuke distributed the whole training session. Then mitch got so mad he did :smite Peng. Which did effect anyone as Peng was an admin as mitch was. That didn't harm the training. It was Peng using :nuke and killing everyone.
Which didn't effect*
Which didn't effect anyone as Peng was an admin*

**Comment by LewisSokoll** [comment]
The Director General and I have decided the following:
**Pengblock** is now demoted from his rank of Chief Superintendent to Suspended.
**Pengblock** has been released of his duties within the Metropolitan Police

This investigation is now closed.

**Comment by EXYZED** [comment]
I approve of the above comment.

**Comment by EXYZED** [comment]
Case to be released to the public
----------------
I hereby declare that this case has been reviewed and amended to public needs, can be distributed around communities and can be discussed upon.
