### ISSUE TITLE
Concerns about the behaviour of R1CH4RDP1PER

### ISSUE THREAD

**Issue by LewisSokoll** [EXYZED/LNDN_PublicDatabase#18]
Over the last 24 hours, R1CH4RD has been displaying rude, cocky and childish behaviour.

Private message from R1CH4RD to myself: http://prntscr.com/etxtsx

R1CH has also been talking about people's families in what can be seen as disrespectful.

Proof sourced from Juniorbest:

http://prntscr.com/etxwek
http://prntscr.com/etxwlu 
http://prntscr.com/etxwpp-

**Comment by EXYZED** [comment]
This investigation is temporarily inactive until further notice.
