### ISSUE TITLE
TSG Mandatory Inspection (Start of inspection 30/3/2017)

### ISSUE THREAD

**Issue by ElChapoCrusader** [EXYZED/LNDN_PublicDatabase#7]
Mandatory Inspection for TSG 8:00GMT. - 31/3/2017
------------------------
Location: Mock Tryouts.
All present must be in full Uniform.

**Assessor** : @ElChapoCrusader 
-Assessor Supervisor : @EXYZED

**Comment by EXYZED** [comment]
Final interview and inspections before the de-commissioning of TSG.
